export interface ProductType {
  id: number;
  name: string;
  price: { first: string; second: string };
  description: string;
  video: string;
  images: string[];
  size?: string | null;
  lost: number;
  inPacket: number;
  preview: string;
  adventages?: string | null;
  hoverImage: string;
}

export const products: ProductType[] = [
  {
    id: 1,
    name: "Наклейки для подписи на контейнер или банку (черные, фигурные)",
    price: {
      first: "45 000",
      second: "35 000",
    },
    description:
      "Эти оригинальные фигурные наклейки идеально подойдут для организации кухни, кладовой или рабочего пространства. Используйте их, чтобы легко маркировать содержимое контейнеров, банок и коробок. Благодаря уникальной форме они придадут вашим предметам эстетичный и аккуратный вид. Наклейки легко приклеиваются и снимаются, не оставляя следов, что позволяет изменять надписи по мере необходимости. Отлично подходят для стеклянных, пластиковых или металлических поверхностей.:",
    video: "",
    images: ["product1", "sticker2", "sticker3"],
    lost: 2,
    inPacket: 8,
    preview: "stickersPreview",
    size: null,
    adventages: "",
    hoverImage: "sticker2",
  },
  {
    id: 2,
    name: "Наклейки для подписи на контейнер или банку (черные, овальные)",
    price: {
      first: "45 000",
      second: "35 000",
    },
    description:
      "Эти оригинальные овальные наклейки идеально подойдут для организации кухни, кладовой или рабочего пространства. Используйте их, чтобы легко маркировать содержимое контейнеров, банок и коробок. Благодаря уникальной форме они придадут вашим предметам эстетичный и аккуратный вид. Наклейки легко приклеиваются и снимаются, не оставляя следов, что позволяет изменять надписи по мере необходимости. Отлично подходят для стеклянных, пластиковых или металлических поверхностей:",
    video: "",
    images: ["product2", "sticker2", "sticker3"],
    lost: 2,
    inPacket: 8,
    preview: "stickersPreview",
    size: null,
    adventages: "",
    hoverImage: "sticker3",
  },
  {
    id: 3,
    name: "Наклейки для подписи (комплект)",
    price: {
      first: "45 000",
      second: "35 000",
    },
    description:
      "Набор фигурных наклеек поможет вам организовать пространство на кухне, в кладовой или офисе. Наклейки представлены в различных формах и идеально подходят для маркировки контейнеров, банок и других емкостей. Используйте меловые маркеры для создания надписей, которые легко стираются, если нужно обновить или заменить содержимое.",
    video: "",
    images: ["product3", "sticker2", "sticker3"],
    lost: 2,
    inPacket: 6,
    preview: "stickersPreview",
    size: null,
    adventages: "",
    hoverImage: "sticker2",
  },
  {
    id: 4,
    name: "Наклейки для подписи (черные, квадратные)",
    price: { first: "75 000 сум", second: "50 000 сум" },
    description:
      "Эти квадратные наклейки созданы для удобной и быстрой маркировки емкостей. Идеально подходят для контейнеров, банок и коробок, они помогают легко организовать пространство на кухне, в кладовой или в офисе. Вы можете подписывать их меловыми маркерами и менять надписи по мере необходимости — всё стирается без следов. Универсальный дизайн и простота в использовании делают их отличным выбором для любого интерьера.",
    video: "",
    images: ["product4", "sticker2", "sticker3"],
    lost: 2,
    inPacket: 12,
    preview: "stickersPreview",
    size: null,
    adventages: "",
    hoverImage: "sticker3",
  },
  {
    id: 5,
    name: "Наклейки для подписи на контейнер или банку (бежевые, фигурные)",
    price: {
      first: "65 000 сум",
      second: "40 000 сум",
    },
    description:
      "Стильные и практичные бежевые наклейки идеально подойдут для маркировки контейнеров, банок и других емкостей на кухне, в кладовой или офисе. Фигурные наклейки помогут вам легко организовать пространство, а нейтральный бежевый цвет гармонично впишется в любой интерьер. Подходят для написания перманентными или меловыми маркерами, надписи можно легко изменить при необходимости.",
    video: "",
    images: ["product5", "sticker2", "sticker3"],
    lost: 2,
    inPacket: 8,
    preview: "stickersPreview",
    size: null,
    adventages: "",
    hoverImage: "sticker2",
  },
  {
    id: 6,
    name: "Наклейки для подписи на контейнер или банку (бежевые, овальные)",
    price: {
      first: "65 000 сум",
      second: "40 000 сум",
    },
    description:
      "Стильные и практичные бежевые наклейки идеально подойдут для маркировки контейнеров, банок и других емкостей на кухне, в кладовой или офисе. Овальные наклейки помогут вам легко организовать пространство, а нейтральный бежевый цвет гармонично впишется в любой интерьер. Подходят для написания перманентными или меловыми маркерами, надписи можно легко изменить при необходимости.",
    video: "",
    images: ["product6", "sticker2", "sticker3"],
    lost: 2,
    inPacket: 8,
    preview: "stickersPreview",
    size: null,
    adventages: "",
    hoverImage: "sticker3",
  },
  {
    id: 7,
    name: "Наклейки для подписи (комплект, черные)",
    price: {
      first: "30 000 сум",
      second: "25 000 сум",
    },
    description:
      "Этот универсальный набор фигурных наклеек включает разнообразные формы, идеально подходящие для маркировки контейнеров, банок и других емкостей. Различные фигуры позволяют подобрать наклейку для любых нужд — от организации кухонных принадлежностей до хранения в кладовой или офисе. Наклейки можно подписывать меловыми или перманентными маркерами, легко стирать и использовать повторно, что делает их отличным решением для практичной и стильной организации пространства.",
    video: "",
    images: ["product7", "sticker2", "sticker3"],
    lost: 2,
    inPacket: 4,
    preview: "stickersPreview",
    size: null,
    adventages: "",
    hoverImage: "sticker2",
  },
  {
    id: 8,
    name: "Наклейки рулон (бежевые)",
    price: {
      first: "300 000 сум",
      second: "200 000 сум",
    },
    description:
      "Практичные и универсальные бежевые наклейки в рулоне идеально подходят для организации хранения и маркировки любых контейнеров и банок. Благодаря нейтральному цвету, они прекрасно вписываются в интерьер кухни, кладовой или офиса. Наклейки легко отрываются от рулона и могут использоваться для маркировки разного типа емкостей.",
    video: "",
    images: ["product8", "sticker2", "sticker3"],
    lost: 2,
    inPacket: 500,
    preview: "stickersPreview",
    size: null,
    adventages: "",
    hoverImage: "sticker3",
  },

  {
    id: 9,
    name: "Карманная шкатулка для украшений ",
    price: { first: "100 000 сум", second: "50 000 сум" },
    description:
      "Карманные шкатулочки для колец и серег — компактное и стильное решение для хранения ваших украшений. Идеально подходит для безопасного хранения колец и серег дома или в поездке.",
    video: "",
    images: ["product9", "caskets2", "caskets3"],
    lost: 2,
    inPacket: 1,
    preview: "casketsPreview1",
    size: "7 x 4 x 5 см",
    adventages:
      " Защищает украшения от потертостей и повреждений • Легко помещается в сумке • Предотвращает потерю украшений",
    hoverImage: "caskets3",
  },
  {
    id: 10,
    name: "Дорожная шкатулка (Черная)",
    price: {
      first: "100 000 сум",
      second: "55 000 сум",
    },
    description:
      "Дорожная шкатулка компактное решение для хранения ваших украшений. Идеально подходит для безопасного хранения в поездке.",
    video: "",
    images: ["product10", "caskets4"],
    lost: 2,
    inPacket: 1,
    preview: "casketsPreview2",
    size: "10 x 10 x 5 см",
    adventages: "",
    hoverImage: "caskets4",
  },
  {
    id: 11,
    name: "Дорожная шкатулка (Розовая, с зеркалом)",
    price: {
      first: "150 000 сум",
      second: "100 000 сум",
    },
    description:
      "Дорожная шкатулка компактное решение для хранения ваших украшений. Идеально подходит для безопасного хранения в поездке.",
    video: "",
    images: ["product11", "caskets5"],
    lost: 2,
    inPacket: 1,
    preview: "casketsPreview3",
    size: "10 x 10 x 5 см",
    adventages:
      "Защищает украшения от потертостей и повреждений • Легко помещается в сумке • Предотвращает потерю украшений",
    hoverImage: "caskets5",
  },
  {
    id: 12,
    name: "Силиконновый зажим для крепления проводов (черный)",
    price: {
      first: "85 000 сум",
      second: "65 000 сум",
    },
    description: "",
    video: "",
    images: ["product12"],
    lost: 2,
    inPacket: 1,
    preview: "",
    size: null,
    adventages: "",
    hoverImage: "",
  },
  {
    id: 13,
    name: "Силиконновый зажим для крепления проводов (белый)",
    price: {
      first: "85 000 сум",
      second: "65 000 сум",
    },
    description: "",
    video: "",
    images: ["product13"],
    lost: 2,
    inPacket: 1,
    preview: "",
    size: null,
    adventages: "",
    hoverImage: "",
  },
  {
    id: 14,
    name: "Зажим для проводов",
    price: {
      first: "85 000 сум",
      second: "70 000 сум",
    },
    description: "",
    video: "",
    images: ["product14"],
    lost: 2,
    inPacket: 14,
    preview: "",
    size: null,
    adventages: "",
    hoverImage: "",
  },
  {
    id: 15,
    name: "Проволочный зажим",
    price: {
      first: "65 000 сум",
      second: "35 000 сум",
    },
    description: "",
    video: "",
    images: ["product15"],
    lost: 2,
    inPacket: 9,
    preview: "",
    size: null,
    adventages: "",
    hoverImage: "",
  },
  {
    id: 16,
    name: "Разделитель для холодильных полок (большой)",
    price: {
      first: "75 000 сум",
      second: "60 000 сум",
    },
    description: "",
    video: "",
    images: ["product16"],
    lost: 2,
    inPacket: 2,
    preview: "",
    size: null,
    adventages: "",
    hoverImage: "",
  },
  {
    id: 17,
    name: "Наклейки для ковров (фигурные)",
    price: {
      first: "150 000 сум",
      second: "100 000 сум",
    },
    description: "",
    video: "",
    images: ["product17"],
    lost: 2,
    inPacket: 4,
    preview: "",
    size: null,
    adventages: "",
    hoverImage: "",
  },
  {
    id: 18,
    name: "Щетка для удаления пятен",
    price: {
      first: "90 000 сум",
      second: "80 000 сум",
    },
    description: "",
    video: "",
    images: ["product18"],
    lost: 2,
    inPacket: 1,
    preview: "",
    size: null,
    adventages: "",
    hoverImage: "",
  },
  {
    id: 19,
    name: "Лопатка для сыпучих",
    price: {
      first: "85 000 сум",
      second: "50 000 сум",
    },
    description: "",
    video: "",
    images: ["product19"],
    lost: 2,
    inPacket: 2,
    preview: "",
    size: null,
    adventages: "",
    hoverImage: "",
  },
  {
    id: 20,
    name: "Разделитель для холодильных полок",
    price: {
      first: "85 000 сум",
      second: "40 000 сум",
    },
    description: "",
    video: "",
    images: ["product20"],
    lost: 2,
    inPacket: 2,
    preview: "",
    size: null,
    adventages: "",
    hoverImage: "",
  },
  {
    id: 21,
    name: "Зажим, крючок для полотенец",
    price: {
      first: "75 000 сум",
      second: "40 000 сум",
    },
    description: "",
    video: "",
    images: ["product21"],
    lost: 2,
    inPacket: 2,
    preview: "",
    size: null,
    adventages: "",
    hoverImage: "",
  },
  {
    id: 22,
    name: "Держатель для швабры",
    price: {
      first: "65 000 сум",
      second: "50 000 сум",
    },
    description: "",
    video: "",
    images: ["product22"],
    lost: 2,
    inPacket: 1,
    preview: "",
    size: null,
    adventages: "",
    hoverImage: "",
  },
  {
    id: 23,
    name: "Силиконовые наклейки для вешалок",
    price: {
      first: "75 000 сум",
      second: "40 000 сум",
    },
    description: "",
    video: "",
    images: ["product23"],
    lost: 2,
    inPacket: 20,
    preview: "",
    size: null,
    adventages: "",
    hoverImage: "",
  },
];
